AREAS = {
    "italy": ["Rhegion", "Taras", "Arpi", "Capua", "Rome", "Arretium", "Ariminum"],
    "sicily": ["Lilibeo", "Messana", "Syracuse"],
    "cisalpine_gaul": ["Patavium", "Bononia", "Mediolanum", "Segesta"],
    "gaul_north": ["Aventicos", "Vesontio", "Bagacos", "Bratosporios", "Cenabum", "Darioritum", "Bibracte"],
    "gaul_south": ["Viennos", "Gergovia", "Tolosa", "Burdigala", "Lemonum", "Avaricum"],
    "massalia": ["Massalia"],
    "iberia_west": ["Gader", "Mastia", "Arse", "Emporion", "Bocchoris", "Baikor"],
    "iberia_east": ["Sucum-Murgi", "Oxtraca", "Tyde", "Pallantia", "Numantia", "Vellika"],
    "britannia": ["Camulosadae", "Ratae", "Caern_Brigantae", "Attuaca", "Ynys_Mon", "Ictis", "Emain_Macha", "Ivernis"],
    "germania": ["Gawjam_Kimbroz", "Gawjam_Habukoz", "Gawjam_Heruskoz", "Arctaunon", "Vindelicoppidos", "Swebotraustastamnoz", "Gawjam_Rugoz", "Gawjam_Skandzawarjoz", "Gawjam_Gotanoz", "Ascaucalis", "Gawjam_Silengoz", "Eburonum", "Carrodunum", "Lucarottea", "Veldideno", "Iuvavoaeta", "Vindobona"],
    "africa_north": ["Lixus", "Siga", "Ippone", "Atiqa", "Kart_Hadast", "Adrumeto", "Lepki"],
    "africa_interior": ["Sala", "Kirtan", "Tuat", "Terhazza", "Garama"],
    "cyrenaica": ["Hibis", "Ammonion", "Paraitonion", "Kyrene", "Augila_settlement"],
    "egypt_north": ["Diospolis_Megale", "Memphis", "Alexandreia"],
    "egypt_south": ["Pselkis", "Meroe", "Ptolemais_Theron", "Axum"],
    "islands": ["Karali", "Alalia", "Kydonia", "Salamis"],
    "arabia": ["Tamane", "Maryab", "Carna", "Sabata", "Ubar", "Homna", "Gerrha", "Petra", "Bostra", "Palmyra"],
    "greece": ["Sparte", "Korinthos", "Athenai", "Chalkis", "Thermon", "Demetrias", "Pella", "Apollonia"],
    "thrace": ["Byzantion", "Tylis", "Serdike"],
    "illyria": ["Epidamnos", "Dalminion", "Segestica"],
    "anatolia": ["Rhodos", "Halikarnassos", "Mytilene", "Pergamon", "Sardis", "Ipsos", "Nikaia", "Ankyra", "Side", "Tarsos", "Mazaka"],
    "armenia": ["Karkathiokerta", "Armavir", "Phraaspa", "Arbela"],
    "pontus": ["Trapezous", "Ani-Kamah", "Sinope", "Amaseia"],
    "dacia": ["Kallatis", "Buridava", "Naissos", "Singidunum", "Sarmiszegethusa", "Ak_Ink"],
    "middle_east": ["Hierosolyma", "Sidon", "Damaskos", "Antiocheia", "Edessa"],
    "sarmatia": ["Chersonesos", "Pantikapaion", "Olbia", "Gawjam_Bastarnoz", "Gordu_Neuriji", "Gintaras_Ostan", "Seliun_Pilis", "Gelonus", "Tanais", "Gava_Yazyga", "Asodat", "Gava_Thissakata", "Gava_Roxsalanna", "Uspe", "Gava_Aursa", "Gava_Yugra", "Kotais", "Mtskheta", "Kabalaka", "Gava_Alanna", "Gava_Saka", "Chighu"],
    "bactria": ["Chach", "Marakanda", "Khiva", "Gava_Mazsakata", "Asaak", "Nisa", "Antiocheia_Margiane", "Baktra", "Alexandreia_Eschate"],
    "mesopotamia": ["Babylon", "Seleukeia", "Charax"],
    "persia": ["Karmana", "Persepolis", "Gabai", "Susa", "Ekbatana", "Apameia", "Hekatompylos", "Zadrakata"],
    "far_east": ["Sulek", "Gava_Haomavarga", "Kophen", "Taksashila", "Alexandropolis", "Opiana", "Patala", "Pura", "Prophthasia", "Alexandreia_Ariana"],
}

#parthia, carthage, gauls, germans, britons, romans_scipii (armenia), dacia, greek_cities, romans_brutii, armenia, spain, thrace
#seleucid, pontus, scythia, saba, macedon, numidia, romans_julii (seleucid?), egypt

BANNED_IN_AREAS = {
    "italy": [],
    "sicily": [],
    "cisalpine_gaul": [],
    "gaul_north": ["germans", "britons"],
    "gaul_south": ["carthage", "germans", "spain"],
    "massalia": [],
    "iberia_west": ["gauls"],
    "iberia_east": ["carthage", "gauls"],
    "britannia": ["gauls"],
    "germania": ["gauls", "dacia", "scythia"],
    "africa_north": ["numidia"],
    "africa_interior": ["carthage"],
    "cyrenaica": ["carthage"],
    "egypt_north": [],
    "egypt_south": [],
    "islands": [],
    "greece": ["dacia"],
    "thrace": ["greek_cities", "macedon"],
    "illyria": ["greek_cities", "macedon"],
    "anatolia": ["parthia", "greek_cities", "thrace", "macedon"],
    "armenia": ["romans_brutii", "scythia"],
    "pontus": ["parthia"],
    "dacia": ["germans", "scythia"],
    "middle_east": ["parthia", "romans_scipii", "pontus"],
    "sarmatia": ["parthia", "romans_scipii", "dacia", "armenia"],
    "bactria": ["scythia"],
    "mesopotamia": ["romans_scipii", "romans_brutii"],
    "persia": ["armenia"],
    "arabia": ["parthia", "seleucid", "romans_julii", "egypt", "seleucid"],
    "far_east": ["parthia"],
}
